# SwiftLint Configuration for LiveAssistant
# Aligned with project standards

# Treat warnings as errors
strict: true

# Paths to exclude from linting
excluded:
  - DerivedData
  - .build
  - build
  - Pods
  - .bundle
  - vendor
  - LiveAssistant.xcodeproj
  - SourcePackages
  - LiveAssistant/Core/Generated  # SwiftGen generated files

# Paths to include (optional, defaults to all Swift files)
included:
  - LiveAssistant
  - LiveAssistantTests
  - LiveAssistantUITests

# Rules to enable
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rules to disable
disabled_rules:
  - todo
  - trailing_whitespace
  - trailing_comma

# Rule configurations
line_length:
  warning: 140
  error: 150
  ignores_function_declarations: false
  ignores_comments: false
  ignores_urls: true

function_parameter_count:
  warning: 6
  error: 9

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3

identifier_name:
  min_length:
    warning: 1
    error: 1
  excluded:
    - id
    - ok
    - db
    - x
    - y
    - z
  allowed_symbols: ["_"]

type_name:
  min_length: 3
  max_length: 50
  allowed_symbols: ["_"]

# Force unwrap warnings
force_cast: warning
force_try: warning
force_unwrapping: warning

# Custom rules
custom_rules:
  double_space:
    name: "Double space"
    regex: "([a-z,A-Z] \\s+)"
    message: "Double space between keywords"
    match_kinds: keyword
    severity: warning

# Reporter type
reporter: "xcode"

