blank_issues_enabled: false
contact_links:
  - name: 🔧 Workflow Guide
    url: https://github.com/ybalashkevych/LiveAssistant/blob/main/WORKFLOW.md
    about: Learn about the development workflow and how to contribute
  - name: 💬 Discussions
    url: https://github.com/ybalashkevych/LiveAssistant/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/ybalashkevych/LiveAssistant/blob/main/README.md
    about: Read the documentation to learn more about LiveAssistant
