name: 🔨 Code Improvement
description: Suggest a refactoring, performance improvement, or code quality enhancement
title: "[Improvement]: "
labels: ["improvement", "technical-debt"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the codebase! Use this template for refactoring, performance improvements, or code quality enhancements.

  - type: dropdown
    id: type
    attributes:
      label: Improvement Type
      description: What type of improvement is this?
      options:
        - Refactoring - Code restructuring
        - Performance - Speed or resource optimization
        - Code Quality - Better patterns or practices
        - Technical Debt - Addressing legacy issues
        - Maintainability - Making code easier to maintain
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be improved and why?
      placeholder: Describe the improvement...
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: Describe the current implementation or situation
      placeholder: |
        Currently, the code...
        
        Location: path/to/file.swift
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: How should it be improved?
      placeholder: |
        The code should be refactored to...
        
        Benefits:
        - Benefit 1
        - Benefit 2
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of this improvement?
      placeholder: |
        - Improved performance by X%
        - Reduced code complexity
        - Better maintainability
        - Easier to test
    validations:
      required: true

  - type: textarea
    id: affected-areas
    attributes:
      label: Affected Areas
      description: What parts of the codebase will be affected?
      placeholder: |
        - Feature/Module/File 1
        - Feature/Module/File 2
    validations:
      required: true

  - type: dropdown
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Will this improvement introduce breaking changes?
      options:
        - "No"
        - "Yes"
        - "Possibly"
    validations:
      required: true

  - type: textarea
    id: breaking-details
    attributes:
      label: Breaking Changes Details
      description: If yes or possibly, explain what breaks and how to migrate
      placeholder: This change will break... Migration steps...

  - type: textarea
    id: testing-strategy
    attributes:
      label: Testing Strategy
      description: How should this improvement be tested?
      placeholder: |
        - Existing tests should pass
        - Add new tests for...
        - Performance benchmarks for...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this improvement to be considered complete?
      placeholder: |
        - [ ] Code is refactored according to plan
        - [ ] All tests pass
        - [ ] Performance meets expectations
        - [ ] Documentation updated
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this improvement?
      options:
        - Low - Nice to have
        - Medium - Should be addressed
        - High - Should be prioritized
        - Critical - Urgent
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, code examples, or benchmarks
      placeholder: Add any relevant information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have identified the specific code that needs improvement
          required: true
        - label: I have considered the impact on existing functionality
          required: true
        - label: I have provided clear acceptance criteria
          required: true

