name: PR Comment Monitor

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  notify-cursor:
    name: Notify Cursor Daemon
    if: github.event.issue.pull_request || github.event.pull_request
    runs-on: ubuntu-latest
    
    steps:
      - name: Get PR number
        id: pr
        run: |
          if [ -n "${{ github.event.issue.number }}" ]; then
            echo "number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ github.event.pull_request.number }}" ]; then
            echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Add needs-changes label
        run: |
          gh pr edit "${{ steps.pr.outputs.number }}" --add-label "needs-changes"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log notification
        run: |
          echo "✅ Added 'needs-changes' label to PR #${{ steps.pr.outputs.number }}"
          echo "Background daemon will process this PR within 60 seconds"

